package com.zdj.jiapu.domain.model;

import java.util.Date;

public class JiapuActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiapuactivity.activityid
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiapuactivity.recordDate
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    private Date recorddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiapuactivity.startDate
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiapuactivity.ownerid
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    private String ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jiapuactivity.message
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiapuactivity.activityid
     *
     * @return the value of jiapuactivity.activityid
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiapuactivity.activityid
     *
     * @param activityid the value for jiapuactivity.activityid
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiapuactivity.recordDate
     *
     * @return the value of jiapuactivity.recordDate
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiapuactivity.recordDate
     *
     * @param recorddate the value for jiapuactivity.recordDate
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiapuactivity.startDate
     *
     * @return the value of jiapuactivity.startDate
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiapuactivity.startDate
     *
     * @param startdate the value for jiapuactivity.startDate
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiapuactivity.ownerid
     *
     * @return the value of jiapuactivity.ownerid
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiapuactivity.ownerid
     *
     * @param ownerid the value for jiapuactivity.ownerid
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid == null ? null : ownerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jiapuactivity.message
     *
     * @return the value of jiapuactivity.message
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jiapuactivity.message
     *
     * @param message the value for jiapuactivity.message
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

	@Override
	public String toString() {
		return "JiapuActivity [activityid=" + activityid + ", recorddate="
				+ recorddate + ", startdate=" + startdate + ", ownerid="
				+ ownerid + ", message=" + message + "]";
	}
    
    
}