package com.zdj.jiapu.domain.repository;

import com.zdj.jiapu.domain.model.JiapuActivity;
import com.zdj.jiapu.domain.model.JiapuActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JiapuActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @SelectProvider(type=JiapuActivitySqlProvider.class, method="countByExample")
    int countByExample(JiapuActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @DeleteProvider(type=JiapuActivitySqlProvider.class, method="deleteByExample")
    int deleteByExample(JiapuActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Delete({
        "delete from jiapuactivity",
        "where activityid = #{activityid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Insert({
        "insert into jiapuactivity (activityid, recordDate, ",
        "startDate, ownerid, ",
        "message)",
        "values (#{activityid,jdbcType=INTEGER}, #{recorddate,jdbcType=DATE}, ",
        "#{startdate,jdbcType=DATE}, #{ownerid,jdbcType=VARCHAR}, ",
        "#{message,jdbcType=VARCHAR})"
    })
    int insert(JiapuActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @InsertProvider(type=JiapuActivitySqlProvider.class, method="insertSelective")
    int insertSelective(JiapuActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @SelectProvider(type=JiapuActivitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="activityid", property="activityid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="recordDate", property="recorddate", jdbcType=JdbcType.DATE),
        @Result(column="startDate", property="startdate", jdbcType=JdbcType.DATE),
        @Result(column="ownerid", property="ownerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="message", property="message", jdbcType=JdbcType.VARCHAR)
    })
    List<JiapuActivity> selectByExample(JiapuActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Select({
        "select",
        "activityid, recordDate, startDate, ownerid, message",
        "from jiapuactivity",
        "where activityid = #{activityid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="activityid", property="activityid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="recordDate", property="recorddate", jdbcType=JdbcType.DATE),
        @Result(column="startDate", property="startdate", jdbcType=JdbcType.DATE),
        @Result(column="ownerid", property="ownerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="message", property="message", jdbcType=JdbcType.VARCHAR)
    })
    JiapuActivity selectByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @UpdateProvider(type=JiapuActivitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") JiapuActivity record, @Param("example") JiapuActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @UpdateProvider(type=JiapuActivitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") JiapuActivity record, @Param("example") JiapuActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @UpdateProvider(type=JiapuActivitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JiapuActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Update({
        "update jiapuactivity",
        "set recordDate = #{recorddate,jdbcType=DATE},",
          "startDate = #{startdate,jdbcType=DATE},",
          "ownerid = #{ownerid,jdbcType=VARCHAR},",
          "message = #{message,jdbcType=VARCHAR}",
        "where activityid = #{activityid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JiapuActivity record);
}