package com.zdj.jiapu.domain.repository;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.zdj.jiapu.domain.model.JiapuActivity;
import com.zdj.jiapu.domain.model.JiapuActivityExample.Criteria;
import com.zdj.jiapu.domain.model.JiapuActivityExample.Criterion;
import com.zdj.jiapu.domain.model.JiapuActivityExample;
import java.util.List;
import java.util.Map;

public class JiapuActivitySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String countByExample(JiapuActivityExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("jiapuactivity");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String deleteByExample(JiapuActivityExample example) {
        BEGIN();
        DELETE_FROM("jiapuactivity");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String insertSelective(JiapuActivity record) {
        BEGIN();
        INSERT_INTO("jiapuactivity");
        
        if (record.getActivityid() != null) {
            VALUES("activityid", "#{activityid,jdbcType=INTEGER}");
        }
        
        if (record.getRecorddate() != null) {
            VALUES("recordDate", "#{recorddate,jdbcType=DATE}");
        }
        
        if (record.getStartdate() != null) {
            VALUES("startDate", "#{startdate,jdbcType=DATE}");
        }
        
        if (record.getOwnerid() != null) {
            VALUES("ownerid", "#{ownerid,jdbcType=VARCHAR}");
        }
        
        if (record.getMessage() != null) {
            VALUES("message", "#{message,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String selectByExample(JiapuActivityExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("activityid");
        } else {
            SELECT("activityid");
        }
        SELECT("recordDate");
        SELECT("startDate");
        SELECT("ownerid");
        SELECT("message");
        FROM("jiapuactivity");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        JiapuActivity record = (JiapuActivity) parameter.get("record");
        JiapuActivityExample example = (JiapuActivityExample) parameter.get("example");
        
        BEGIN();
        UPDATE("jiapuactivity");
        
        if (record.getActivityid() != null) {
            SET("activityid = #{record.activityid,jdbcType=INTEGER}");
        }
        
        if (record.getRecorddate() != null) {
            SET("recordDate = #{record.recorddate,jdbcType=DATE}");
        }
        
        if (record.getStartdate() != null) {
            SET("startDate = #{record.startdate,jdbcType=DATE}");
        }
        
        if (record.getOwnerid() != null) {
            SET("ownerid = #{record.ownerid,jdbcType=VARCHAR}");
        }
        
        if (record.getMessage() != null) {
            SET("message = #{record.message,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("jiapuactivity");
        
        SET("activityid = #{record.activityid,jdbcType=INTEGER}");
        SET("recordDate = #{record.recorddate,jdbcType=DATE}");
        SET("startDate = #{record.startdate,jdbcType=DATE}");
        SET("ownerid = #{record.ownerid,jdbcType=VARCHAR}");
        SET("message = #{record.message,jdbcType=VARCHAR}");
        
        JiapuActivityExample example = (JiapuActivityExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    public String updateByPrimaryKeySelective(JiapuActivity record) {
        BEGIN();
        UPDATE("jiapuactivity");
        
        if (record.getRecorddate() != null) {
            SET("recordDate = #{recorddate,jdbcType=DATE}");
        }
        
        if (record.getStartdate() != null) {
            SET("startDate = #{startdate,jdbcType=DATE}");
        }
        
        if (record.getOwnerid() != null) {
            SET("ownerid = #{ownerid,jdbcType=VARCHAR}");
        }
        
        if (record.getMessage() != null) {
            SET("message = #{message,jdbcType=VARCHAR}");
        }
        
        WHERE("activityid = #{activityid,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapuactivity
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    protected void applyWhere(JiapuActivityExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}