package com.zdj.jiapu.domain.repository;

import com.zdj.jiapu.domain.model.JiapuMessage;
import com.zdj.jiapu.domain.model.JiapuMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JiapuMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @SelectProvider(type=JiapuMessageSqlProvider.class, method="countByExample")
    int countByExample(JiapuMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @DeleteProvider(type=JiapuMessageSqlProvider.class, method="deleteByExample")
    int deleteByExample(JiapuMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Delete({
        "delete from jiapumessage",
        "where messageid = #{messageid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Insert({
        "insert into jiapumessage (messageid, createDate, ",
        "message, senderid, ",
        "recieverid)",
        "values (#{messageid,jdbcType=INTEGER}, #{createdate,jdbcType=DATE}, ",
        "#{message,jdbcType=VARCHAR}, #{senderid,jdbcType=VARCHAR}, ",
        "#{recieverid,jdbcType=VARCHAR})"
    })
    int insert(JiapuMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @InsertProvider(type=JiapuMessageSqlProvider.class, method="insertSelective")
    int insertSelective(JiapuMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @SelectProvider(type=JiapuMessageSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="messageid", property="messageid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="createDate", property="createdate", jdbcType=JdbcType.DATE),
        @Result(column="message", property="message", jdbcType=JdbcType.VARCHAR),
        @Result(column="senderid", property="senderid", jdbcType=JdbcType.VARCHAR),
        @Result(column="recieverid", property="recieverid", jdbcType=JdbcType.VARCHAR)
    })
    List<JiapuMessage> selectByExample(JiapuMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Select({
        "select",
        "messageid, createDate, message, senderid, recieverid",
        "from jiapumessage",
        "where messageid = #{messageid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="messageid", property="messageid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="createDate", property="createdate", jdbcType=JdbcType.DATE),
        @Result(column="message", property="message", jdbcType=JdbcType.VARCHAR),
        @Result(column="senderid", property="senderid", jdbcType=JdbcType.VARCHAR),
        @Result(column="recieverid", property="recieverid", jdbcType=JdbcType.VARCHAR)
    })
    JiapuMessage selectByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @UpdateProvider(type=JiapuMessageSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") JiapuMessage record, @Param("example") JiapuMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @UpdateProvider(type=JiapuMessageSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") JiapuMessage record, @Param("example") JiapuMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @UpdateProvider(type=JiapuMessageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JiapuMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiapumessage
     *
     * @mbggenerated Tue Apr 14 18:46:15 CST 2015
     */
    @Update({
        "update jiapumessage",
        "set createDate = #{createdate,jdbcType=DATE},",
          "message = #{message,jdbcType=VARCHAR},",
          "senderid = #{senderid,jdbcType=VARCHAR},",
          "recieverid = #{recieverid,jdbcType=VARCHAR}",
        "where messageid = #{messageid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JiapuMessage record);
}